# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: '3.6'
services:
  app:
    image: zsh-projects-app-test
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
